# Generated by Django 5.0.6 on 2024-06-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="myuser",
            table="User",
        ),
    ]
